name: Agent CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]
    paths-ignore:
      -  'frontend/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - uses: Gr1N/setup-poetry@v7

      - name: Load images from cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: foo-docker-cache-{hash}
          restore-keys: foo-docker-cache-

      - name: Start local Optimism chain
        run: bash docker/optimism/optimism.sh up

